data:
  data_path: 'data/USPTO_50K_PtoR_aug20'
  task: 'backward_prediction'

model:
  # architecture parameters
  d_model: 64
  num_layers: 2
  num_heads: 2
  d_feedforward: 64
  activation: 'gelu'
  max_seq_len: 256
  dropout: 0.1

  #diffusion parameters
  continuous: True
  num_timesteps: 200
  beta_schedule: 'cosine'
  # loss_terms: ['mse','vb']
  loss_terms: ['elbo', 'nll']
  rate_model: 'Uniform'
  min_time: 0.01
  length_loss: 'cross_entropy'
  pad_limit: 20
  diffuseq: false

  #continuous model parameters
  rate_const: 0.03
  rate_sigma: 3.0
  Q_sigma: 20.0
  time_exponential: 1000.0
  time_base: 0.5
  sigma_min: 1.0
  sigma_max: 100.0
  
training:
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.0
  epochs: 30
  patience: 30
  gpus: 1
  