data:
  data_path: 'data/USPTO_50K_PtoR_aug20'
  task: 'backward_prediction'
  pad_limit: null

model:
  # architecture parameters
  d_model: 512
  num_layers: 6
  num_heads: 8
  d_feedforward: 2048
  activation: 'gelu'
  max_seq_len: 256
  dropout: 0.1

  # loss parameters
  length_loss: 'cross_entropy'
  coeff_ce: 1.0
  coeff_vlb: 1.0

  #diffusion parameters
  continuous: True
  num_timesteps: 200
  min_time: 0.01
  noise_schedule: 'loglinear'
  noise_schedule_args: {}

training:
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.0
  epochs: 30
  patience: 30
  gpus: 1  
  